//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citas_Medicas
    {
        public int idCita { get; set; }
        public System.DateTime fecha { get; set; }
        public string estadoDeLaCita { get; set; }
        public Nullable<System.TimeSpan> duracion { get; set; }
        public bool Consulta_EnLinea { get; set; }
        public string Paciente_DNI { get; set; }
        public int HospitalMedico_Medico_idMedico { get; set; }
        public int HospitalMedico_Hospital_idHospital { get; set; }
    
        public virtual HospitalMedico HospitalMedico { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
