//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Informacion_Adm
    {
        public int idInformacion { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public int Hospital_idHospital { get; set; }
    
        public virtual Hospital Hospital { get; set; }
    }
}
