//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbTFEntities : DbContext
    {
        public dbTFEntities()
            : base("name=dbTFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Beneficios> Beneficios { get; set; }
        public virtual DbSet<Citas_Medicas> Citas_Medicas { get; set; }
        public virtual DbSet<Comentario> Comentario { get; set; }
        public virtual DbSet<Especialidad> Especialidad { get; set; }
        public virtual DbSet<Hospital> Hospital { get; set; }
        public virtual DbSet<HospitalMedico> HospitalMedico { get; set; }
        public virtual DbSet<Informacion_Adm> Informacion_Adm { get; set; }
        public virtual DbSet<Medico> Medico { get; set; }
        public virtual DbSet<Notificaciones> Notificaciones { get; set; }
        public virtual DbSet<Paciente> Paciente { get; set; }
        public virtual DbSet<Respuesta> Respuesta { get; set; }
        public virtual DbSet<Servicios> Servicios { get; set; }
        public virtual DbSet<Volunraio> Volunraio { get; set; }
    }
}
